version: "3"

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: slin
      POSTGRES_DB: sample_postgres_development
    ports:
      - 5431:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080